package org.openflux.app.data

enum class SshAuthMethod { PASSWORD, KEY }
// HTTP mode skips Nginx/TLS entirely: install.sh binds controlplane straight to 0.0.0.0:8080 in plain HTTP.
enum class TlsMode { DOMAIN, IP, HTTP }
enum class DeployStatus { NONE, RUNNING, SUCCESS, FAILED }

// [DeployServerEntity]'s non-secret fields joined with the secrets in [DeployServerSecretsStore] for the same id.
data class DeployServer(
    val id: String = "",
    val name: String = "",
    val host: String = "",
    val port: Int = 22,
    val username: String = "root",
    val authMethod: SshAuthMethod = SshAuthMethod.PASSWORD,
    val sshPassword: String = "",
    val sshPrivateKeyPem: String = "",
    val sshPassphrase: String = "",
    val tlsMode: TlsMode = TlsMode.IP,
    val domain: String = "",
    val email: String = "",
    val repoUrl: String = "https://github.com/wlruscfd/openflux-server.git",
    val gitRef: String = "main",
    val deployScriptUrl: String = "https://raw.githubusercontent.com/wlruscfd/openflux-deploy/main/install.sh",
    val registerNode: Boolean = true,
    val nodeName: String = "node-1",
    val nodeMaxKeys: Int = 500,
    // Off only for a deliberate multi-server split where the exit node runs elsewhere.
    val runNodeHere: Boolean = true,
    // Generated by the app itself (see DeployServerRepository.save), not left for install.sh to invent.
    val adminToken: String = "",
    val dbPassword: String = "",
    // Generated remotely and shown exactly once; this is the only copy the app ever has of it.
    val nodeToken: String = "",
    val knownHostKeyFingerprint: String = "",
    val lastDeployStatus: DeployStatus = DeployStatus.NONE,
    val lastDeployAt: Long = 0,
) {
    /** Where this server's controlplane (once deployed) is reachable. */
    val baseUrl: String get() = when (tlsMode) {
        TlsMode.DOMAIN -> "https://$domain"
        TlsMode.IP -> "https://$host"
        // No Nginx in front of it in this mode, so hit controlplane's own port directly.
        TlsMode.HTTP -> "http://$host:8080"
    }
}
